-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 16:14:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `locadora` ;

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora` DEFAULT CHARACTER SET utf8mb4 ;
USE `locadora` ;

-- -----------------------------------------------------
-- Table `locadora`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `rg` VARCHAR(20) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(145) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT(11) NOT NULL,
  `cep` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `locadora`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `locadora`.`classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`classificacao` (
  `idclassificacao` INT(11) NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`idclassificacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `locadora`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`filme` (
  `idfilme` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `ano` INT(11) NULL DEFAULT NULL,
  `duracao` VARCHAR(10) NULL DEFAULT NULL,
  `idcategoria` INT(11) NOT NULL,
  `idclassificacao` INT(11) NOT NULL,
  `capa` VARCHAR(80) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfilme`),
  INDEX `idcategoria` (`idcategoria` ASC) VISIBLE,
  INDEX `idclassificacao` (`idclassificacao` ASC) VISIBLE,
  CONSTRAINT `filme_ibfk_1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `locadora`.`categoria` (`idcategoria`),
  CONSTRAINT `filme_ibfk_2`
    FOREIGN KEY (`idclassificacao`)
    REFERENCES `locadora`.`classificacao` (`idclassificacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `locadora`.`dvd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`dvd` (
  `iddvd` INT(11) NOT NULL AUTO_INCREMENT,
  `idfilme` INT(11) NOT NULL,
  `preco_compra` DOUBLE NULL DEFAULT NULL,
  `data_compra` VARCHAR(10) NULL DEFAULT NULL,
  `situacao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`iddvd`),
  INDEX `idfilme` (`idfilme` ASC) VISIBLE,
  CONSTRAINT `dvd_ibfk_1`
    FOREIGN KEY (`idfilme`)
    REFERENCES `locadora`.`filme` (`idfilme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `locadora`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`aluguel` (
  `idaluguel` INT(11) NOT NULL AUTO_INCREMENT,
  `iddvd` INT(11) NOT NULL,
  `idcliente` INT(11) NOT NULL,
  `hora_aluguel` VARCHAR(10) NOT NULL,
  `data_aluguel` VARCHAR(10) NOT NULL,
  `data_devolucao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idaluguel`),
  INDEX `idcliente` (`idcliente` ASC) VISIBLE,
  INDEX `iddvd` (`iddvd` ASC) VISIBLE,
  CONSTRAINT `aluguel_ibfk_1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `locadora`.`cliente` (`idcliente`),
  CONSTRAINT `aluguel_ibfk_2`
    FOREIGN KEY (`iddvd`)
    REFERENCES `locadora`.`dvd` (`iddvd`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `locadora`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`funcionario` (
  `idfuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
